[server]
# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 200

# Max size, in megabytes, of messages that can be sent via the WebSocket connection.
# Default: 200
maxMessageSize = 200

[theme]
primaryColor="c9eab8"
backgroundColor="#ffffff"
secondaryBackgroundColor="def1d5"
textColor="#000000"
font="sans serif"
