[server]
# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 200

# Max size, in megabytes, of messages that can be sent via the WebSocket connection.
# Default: 200
maxMessageSize = 200

[theme]
primaryColor="41a5ee"
backgroundColor="#ffffff"
secondaryBackgroundColor="33c481"
textColor="#000000"
font="sans serif"
