[server]
# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 50

# Max size, in megabytes, of messages that can be sent via the WebSocket connection.
# Default: 200
maxMessageSize = 200

[theme]
primaryColor="41a5ee"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#ebd7f0"
#secondaryBackgroundColor="#590d7a"
#textColor="#D3D3D3"
textColor="#344a80"
font="sans-serif"

# https://www.color-meanings.com/shades-of-gray-color-names-html-hex-rgb-codes/
# https://www.canva.com/colors/color-wheel/
